### ISSUE TITLE
[Bug]: 2 Channels not sending with shouldSend()

### ISSUE THREAD

**Issue by greeto** [spatie/laravel-notification-log#22]
### What happened?

    public function shouldSend($notifiable)
    {
        return $this
            ->wasNotSentTo($notifiable)
            ->inThePastMinutes(30);
    }
    
    public function via($notifiable){ 
    return ['mail', MyCustomChannel:class]
    }

### How to reproduce the bug

Put 2 Channels (1 custom, 1 regular) in 'via'

### Package Version

1.0.4

### PHP Version

8.1

### Laravel Version

10

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this!

**Comment by pxlrbt** [comment]
@freekmurze Do you consider this a bug? I don't think people expect that `wasSentTo()` returns a different result for the second channel.

**Comment by freekmurze** [comment]
We'll handle this in #23
