### ISSUE TITLE
[Bug]: Database table column "exception_message" not used

### ISSUE THREAD

**Issue by andreasnij** [spatie/laravel-notification-log#29]
### What happened?

The database table column "exception_message" seems to be unused. I'm not sure if the code meant to put data in it is missing or the column was added by misstake.

### How to reproduce the bug

Search code base for `exception_message`.

### Package Version

1.1.1

### PHP Version

8.2

### Laravel Version

10

**Comment by freekmurze** [comment]
Feel free to PR the removal of that column. If the test will pass, I'll merge it!
