### ISSUE TITLE
[Bug]: wasAlreadySentTo method missing which is mentioned in documentation

### ISSUE THREAD

**Issue by yarwoob** [spatie/laravel-notification-log#42]
### What happened?

https://spatie.be/docs/laravel-notification-log/v1/introduction page mentions the `wasAlreadySentTo` method but this does not seem to exist in the code.  Should probably be` wasSentTo` method in the HasHistory trait.

### How to reproduce the bug

Documentation error 

### Package Version

2.0.0

### PHP Version

8.2.0

### Laravel Version

10.0.0

### Which operating systems does with happen with?

macOS, Windows, Linux

**Comment by freekmurze** [comment]
Fixed: https://github.com/spatie/laravel-notification-log/blob/main/docs/introduction.md
