### ISSUE TITLE
[Bug]: Model with UUID will not able to log as notifiable

### ISSUE THREAD

**Issue by balazs1396** [spatie/laravel-notification-log#9]
### What happened?

If the notifiable model have different type of id like unsignedBigInteger, database error will be occurred. 

### How to reproduce the bug

Try to create NotificationLogItem with notifiable whose primary id is not a unsignedBigInteger

### Package Version

main

### PHP Version

8.2.0

### Laravel Version

10.0.0

### Which operating systems does with happen with?

Linux

**Comment by npw1982** [comment]
We've got this issue too, not a bug I wouldn't say, but would be a nice to have feature.
